// Player-facing text for the core content. The writer (WP 1.8) owns the strings in this file; the
// economy WP (1.5) owns its exported SHAPES (keep them): UNIT_TEXT, UPGRADE_TEXT, dragonName,
// sizeWord, MICROCOPY; and (M2, core WP 2.0) TIER_TEXT, BOSS_TEXT, CHAMPION_TEXT, CHARGE_TEXT,
// ABILITY_TEXT, heightWord. The M2 strings are the writer's (WP 2.11).
// Pure: no randomness except the injected `rand`, no imports beyond core types.
// Effect lines ("Click damage ×2") are generated by the UI from data; never write them as flavor.
// Voice: epic with a wink. Awe first, then a dry joke. One line each.
import type { AbilityId, ChampionId, ChargeId, UnitId, UpgradeId } from '../types';

export const UNIT_TEXT: Record<UnitId, { name: string; plural: string; flavor: string }> = {
  footman: { name: 'Footman', plural: 'Footmen', flavor: 'Sworn to the meadow. Paid in soup. Brave, mostly.' },
  archer: { name: 'Archer', plural: 'Archers', flavor: 'Aims for the eye. Hits the dragon. Counts it.' },
  lancer: { name: 'Lancer', plural: 'Lancers', flavor: 'A knight, a horse and a very long argument, settled at a gallop.' },
};

export const UPGRADE_TEXT: Record<UpgradeId, { name: string; flavor: string }> = {
  pointySwords: { name: 'Pointier Swords', flavor: 'Research confirms the pointy end is the important end.' },
  keenEye: { name: 'Keen Eye', flavor: 'Every dragon has one loose scale. Knights are trained to take it personally.' },
  drillSergeant: { name: 'Drill Sergeant', flavor: 'Left, right, stab. Left, right, stab. Left, right, soup.' },
  bounty: { name: 'Bounty Notices', flavor: 'WANTED: dragons, any size. Please do not bring them in alive.' },
  fletching: { name: 'Honest Fletching', flavor: 'The feathers go at the back. This changes everything.' },
  warHorns: { name: 'War Horns', flavor: 'One long blast means charge. Two means lunch. Nobody knows three.' },
  heroicExample: { name: 'Heroic Example', flavor: 'Where your sword goes, a hundred follow. Mostly in the right direction.' },
  quickNock: { name: 'Quick Nock', flavor: 'Aiming has been reclassified as optional.' },
  grindstone: { name: 'Grindstone', flavor: 'The blacksmith sharpened it until it hummed. Then a bit more.' },
  // The Mountain's set. Knights stand ~200 m tall here: pine forests are moss, clouds are knee-deep.
  highForge: { name: 'High Forge', flavor: 'Your blade, reforged above the clouds. The smiths are lightheaded. The sword is not.' },
  pikeWall: { name: 'Pike Wall', flavor: 'Pikes a kilometre long, held very still. The dragon is welcome to keep walking.' },
  yewLongbows: { name: 'Yew Longbows', flavor: 'Each bow is a whole yew forest, strung. The foresters have questions.' },
  mountainTithe: { name: 'Mountain Tithe', flavor: 'The peaks pay in gold. The peaks do not know this yet.' },
  couchedLances: { name: 'Couched Lances', flavor: 'Tuck it under the arm. Point it at the problem. Gallop.' },
  destriers: { name: 'Destriers', flavor: 'Warhorses bred for speed, courage and not looking down.' },
};

// ---- Dragon names ----
// A name is: [honorific] stem [numeral] + epithet. Size "band" 0/1/2 (newt / cart / barn) is
// drawn from the dragon's index with some bleed, so early epithets are earnest and ankle-high and
// later ones get grand. Mismatches ("Doom of Toes", "Wee Vexathrax") are a feature.
// Epithet join rule: an epithet that starts with "," (", Who...", ", Bane of...") attaches with no
// space; anything else attaches with one space. An empty epithet means the name stands alone.

type Band = readonly [readonly string[], readonly string[], readonly string[]];

/** Full names with a homely ring. */
const STEMS_SILLY: readonly string[] = [
  'Pumpernickel', 'Smoulderbottom', 'Gribble', 'Nibwort', 'Snorrow', 'Pip', 'Cinderwick', 'Brisket',
  'Puddlefoot', 'Wobbleton', 'Crumpet', 'Fennimore', 'Blotch', 'Mudge', 'Dumpling', 'Sizzleby',
  'Bramblegut', 'Pottage', 'Fizzwick', 'Hobnail', 'Grumbleweed', 'Parsnip', 'Kettle', 'Gherkin',
  'Truffle', 'Gerald', 'Mildred', 'Humphrey', 'Barnaby', 'Maud', 'Tarragon', 'Scorchwhistle',
];
const SILLY_HEAD: readonly string[] = [
  'Snor', 'Grib', 'Nib', 'Wob', 'Mud', 'Crum', 'Fizz', 'Dob', 'Wimble', 'Gub', 'Pim', 'Bog', 'Tum', 'Sniv', 'Pudd', 'Smudge',
];
const SILLY_TAIL: readonly string[] = [
  'kin', 'wort', 'wick', 'snout', 'muffin', 'belly', 'puff', 'wump', 'toes', 'bottom', 'sock', 'nose', 'crumb', 'whistle',
];
/** Names that sound like they have a lair. */
const STEMS_GRAND: readonly string[] = [
  'Vexathrax', 'Ignorath', 'Malgrimm', 'Cindraxis', 'Embersnatch', 'Brimstoke', 'Pyrrhonax', 'Scathaxa',
  'Morgrath', 'Ashenvile', 'Thornmaw', 'Skorvald', 'Obsidax', 'Grendelwick', 'Umbraxis', 'Kragmire',
];
const GRAND_HEAD: readonly string[] = [
  'Vex', 'Ign', 'Mal', 'Skor', 'Zar', 'Krag', 'Vorn', 'Ash', 'Pyr', 'Umbr', 'Brim', 'Sarth', 'Thar', 'Cindr', 'Grax', 'Scald',
];
const GRAND_TAIL: readonly string[] = [
  'athrax', 'orath', 'ith', 'ax', 'uul', 'avax', 'anox', 'ivex', 'azar', 'endrax', 'oth', 'ixis', 'emor', 'ungrim',
];

const HONORIFICS: Band = [
  ['Little', 'Wee', 'Young', 'Tiny', 'Cousin', 'Auntie', 'Old', 'Baby'],
  ['Big', 'Uncle', 'Madam', 'Mister', 'Old', 'Great-Aunt', 'Sergeant'],
  ['Old', 'Great', 'Lord', 'Lady', 'Grandmother', 'Baron', 'Duchess', 'Archduke'],
];
const NUMERALS: readonly string[] = ['II', 'III', 'IV', 'VII', 'IX', 'XII', 'XIV'];

const THE_ADJ: Band = [
  [
    'the Unready', 'the Damp', 'the Mildly Singed', 'the Pocket-Sized', 'the Brief', 'the Slightly Warm',
    'the Easily Startled', 'the Ankle-High', 'the Earnest', 'the Hopeful', 'the Soggy', 'the Unimposing',
    'the Squeaky', 'the Wriggly', 'the Lukewarm', 'the Nearly Fearsome', 'the Adequate', 'the Bite-Sized',
    'the Small (but Keen)', 'the Harmless-Looking',
  ],
  [
    'the Moderately Fearsome', 'the Unexpectedly Loud', 'the Upwardly Mobile', 'the Recently Promoted',
    'the Not-So-Little', 'the Inconvenient', 'the Rude', 'the Suspiciously Large', 'the Considerable',
    'the Mildly Alarming', 'the Smouldering', 'the Still Growing', 'the Combustible', 'the Ambitious',
    'the Fence-Flattener', 'the Subject of Several Complaints',
  ],
  [
    'the Dread', 'the Magnificent', 'the Unburnt', 'the Vast', 'the Enormous (Relatively)',
    'the Terrible (at Hiding)', 'the Ruinous', 'the Colossal', 'the Frankly Enormous', 'the Sky-Darkening',
    'the Thunderous', 'the Undefeated (So Far)', 'the Barn-Wrecker', 'the Unquestionably Large',
    'the Grim', 'the Uninsurable',
  ],
];

const WHO: Band = [
  [
    ', Who Bites Ankles', ', Who Is Doing Their Best', ', Who Fits in a Boot', ', Who Sneezes Sparks',
    ', Who Would Like a Word', ', Who Has a Very Small Hoard', ', Who Is Allowed on the Furniture', ', Who Hisses Politely',
    ', Who Is Mostly Tail', ', Who Once Set Fire to a Leaf', ", Who Thinks It's a Wolf",
    ', Who Could Take You, Probably', ', Who Stole a Spoon', ', Who Glares at Ducks',
    ', Who Is Technically a Dragon', ', Who Has Been Practising Roaring',
  ],
  [
    ', Who Has Eaten a Fence', ', Who Hoards Spoons', ', Who Frightens Sheep for Sport',
    ', Who Outgrew the Pond', ', Who No Longer Fits in Boots', ', Who Is Having a Growth Spurt',
    ', Who Sits on Haystacks', ', Who Has Read One Book About Knights', ', Who Owes the Miller a Windmill',
    ', Who Roars at Weddings', ', Who Is Banned From the Fair', ', Who Eats Carts, Wheels First',
  ],
  [
    ', Who Mostly Eats Villages on Tuesdays', ', Who Blots Out the Sun, Locally', ', Who Remembers Your Grandfather',
    ', Who Has Never Lost a Staring Contest', ', Who Sleeps on a Hoard of Helmets', ', Who Was Promised a Princess',
    ', Who Topples Steeples Recreationally', ', Who Is Owed Several Castles', ', Who Burned Both Bridges',
    ', Who Answers to No One, Loudly', ', Who Has Outgrown Three Lairs', ', Who Casts Shade at Noon',
  ],
];

const ROLES: Band = [
  ['Eater of', 'Nibbler of', 'Menace to', 'Chewer of', 'Pest of', 'Warmer of', 'Hisser at'],
  ['Eater of', 'Bane of', 'Terror of', 'Scorcher of', 'Menace to', 'Flattener of', 'Scourge of'],
  ['Scourge of', 'Doom of', 'Despoiler of', 'Devourer of', 'Bane of', 'Terror of', 'Unmaker of', 'Burner of'],
];
const THINGS: Band = [
  [
    'Picnics', 'Ankles', 'Ducks', 'Beetles', 'Lettuces', 'Toes', 'Pies Left on Sills', 'One (1) Sheep',
    'the Duck Pond', 'Dandelions', 'Bootlaces', 'Crumbs', 'the Vegetable Patch', 'Unattended Sandwiches',
  ],
  [
    'Fences', 'Hay Carts', 'Scarecrows', 'Sheep (Several)', 'Windmills', 'the Lower Meadow', 'Hedgerows',
    'Weddings', 'Market Day', "the Miller's Patience", 'Haystacks', 'Chickens, Wholesale',
  ],
  [
    'Barns', 'Castles', 'Three Counties', 'Kings (Two)', 'Whole Villages', 'the Harvest', 'Cathedrals',
    'Knights, Mostly', 'the Western Shires', 'Entire Afternoons', 'Bridges', 'Several Heroes',
  ],
];

const PLACES: Band = [
  [
    'of the Puddle', 'of the Long Grass', 'of the Third Pond on the Left', 'of the Soggy Bottom',
    'of Under the Rock', 'of the Compost Heap', 'of the Buttercups', 'of the Damp Log',
  ],
  ['of the Mill Pond', 'of the Hayloft', 'of the Old Stone Wall', 'of the Muddy Lane', 'of the Burnt Orchard'],
  [
    'of the Burning Hills', 'of the Seven Chimneys', 'of the High Pastures', 'of the Smoking Vale', 'of the Far Hills',
    'of the Scorched Earth (Parts)', 'of the Long Shadow', 'of the Ashen Downs', 'of the Unmapped North',
  ],
];

const ORDINALS: readonly string[] = [
  'the Third, Probably', 'the Second (the First Ran Off)', 'the Fourth of That Name', 'the Fifth, Allegedly',
  'the Eleventh (Do Not Ask)', 'the First and Hopefully Last', 'the Younger (by Minutes)', 'the Twelfth, Counting Cousins',
  'Junior', 'the Sequel', 'the Ninth (the Others Were Worse)', 'the Umpteenth', 'the Latest', 'the Second, Again',
];

/** Hand-picked names for the very first newt: the judge reads this one at 0:05. */
const FIRST_NEWTS: readonly (readonly [string, string])[] = [
  ['Pumpernickel', 'the Unready'],
  ['Nibwort', ', Who Is Doing Their Best'],
  ['Gribble', ', Eater of One (1) Sheep'],
  ['Pip', ', Menace to Ankles'],
  ['Crumpet', 'the Mildly Singed'],
  ['Wee Vexathrax', ''],
  ['Gerald', 'the Dread'],
  ['Tarragon', 'the Slightly Warm'],
  ['Old Puddlefoot', 'the Damp'],
  ['Smoulderbottom', ", Who Thinks It's a Wolf"],
  ['Mildred', 'the Nearly Fearsome'],
  ['Little Ignorath', ', Who Fits in a Boot'],
];

function pick<T>(rand: () => number, list: readonly T[]): T {
  return list[Math.floor(rand() * list.length) % list.length]!;
}

/** Size band for this dragon: rises with index (barn-sized by ~27), with a little bleed either way. */
function bandOf(rand: () => number, index: number): 0 | 1 | 2 {
  const x = Math.min(1, Math.max(0, index) / 26) + (rand() - 0.5) * 0.5;
  return x < 0.34 ? 0 : x < 0.67 ? 1 : 2;
}

/** Head + tail, avoiding a doubled letter at the seam ("Wobbottom"). */
function join(rand: () => number, heads: readonly string[], tails: readonly string[]): string {
  const head = pick(rand, heads);
  let tail = pick(rand, tails);
  if (head.slice(-1).toLowerCase() === tail.charAt(0)) tail = pick(rand, tails);
  return head + tail;
}

function stem(rand: () => number, band: 0 | 1 | 2): string {
  const silly = rand() < [0.7, 0.5, 0.35][band]!;
  if (silly) return rand() < 0.6 ? pick(rand, STEMS_SILLY) : join(rand, SILLY_HEAD, SILLY_TAIL);
  return rand() < 0.4 ? pick(rand, STEMS_GRAND) : join(rand, GRAND_HEAD, GRAND_TAIL);
}

function compose(rand: () => number, index: number): { name: string; epithet: string } {
  const band = bandOf(rand, index);
  let name = stem(rand, band);
  const honorific = rand() < 0.2;
  if (honorific) name = pick(rand, HONORIFICS[band]) + ' ' + name;
  const numeral = !honorific && rand() < 0.04;
  if (numeral) name += ' ' + pick(rand, NUMERALS);
  if (honorific && rand() < 0.35) return { name, epithet: '' }; // "Old Smoulderbottom" needs nothing else

  const r = rand();
  const eb = bandOf(rand, index); // the epithet rolls its own band: "Wee Vexathrax, Doom of Toes"
  let epithet: string;
  if (r < 0.34) epithet = pick(rand, THE_ADJ[eb]);
  else if (r < 0.58) epithet = pick(rand, WHO[eb]);
  else if (r < 0.84) epithet = ', ' + pick(rand, ROLES[eb]) + ' ' + pick(rand, THINGS[bandOf(rand, index)]);
  else if (r < 0.93 || numeral) epithet = pick(rand, PLACES[eb]);
  else epithet = pick(rand, ORDINALS);
  return { name, epithet };
}

/**
 * Name the nth dragon of a species. Pure: all variation comes from `rand` ([0, 1), seeded by the
 * core), so the same save always names the same dragons. `index` is the dragon's number in its
 * tier (0 = the very first newt), for names that escalate with size.
 * Display: name + (epithet starts with ',' ? '' : ' ') + epithet.
 */
export function dragonName(rand: () => number, species: string, index: number): { name: string; epithet: string } {
  if (species === 'newt' && index <= 0) {
    const [name, epithet] = pick(rand, FIRST_NEWTS);
    return { name, epithet };
  }
  // Keep most names HUD-friendly (≤ 40 chars); a long one survives now and then for the laugh.
  let out = compose(rand, index);
  for (let i = 0; i < 4 && out.name.length + out.epithet.length + 1 > 40 && rand() > 0.2; i++) out = compose(rand, index);
  return out;
}

// ---- Size ----
// Dragon lengths in DISPLAY meters. The Meadow runs newt → hill; the Mountain's wyverns run from
// ~150 m to several km (bosses ×1.5); the rungs past that are cheap headroom for the Kingdom and Sky.
const SIZE_BANDS: readonly (readonly [number, string])[] = [
  [0.65, 'newt-sized'],
  [0.85, 'cat-sized, and twice as smug'],
  [1.15, 'dog-sized'],
  [1.6, 'dog-sized, and not a good dog'],
  [2.1, 'pony-sized'],
  [3, 'horse-sized'],
  [4.5, 'hay-cart-sized'],
  [7, 'cottage-sized'],
  [12, 'barn-sized'],
  [19, 'the size of a barn, if the barn were angry'],
  [30, 'chapel-sized; please remove your helmet'],
  [50, 'cathedral-sized'],
  [90, 'hill-sized. The hill has concerns.'],
  // The Mountain.
  [160, 'the size of a watchtower, and watching you back'],
  [320, 'castle-sized, moat included'],
  [650, 'the size of a market town, on market day'],
  [1200, "the size of a crag, with a crag's manners"],
  [2500, 'glacier-sized, and about as quick to forgive'],
  [5000, 'mountain-sized, give or take a mountain'],
  [10000, 'the size of a mountain range, lying down'],
  [25000, 'as long as a valley, and in a worse mood'],
  [60000, 'county-sized; the county has been informed'],
  // Headroom for the Kingdom and the Sky.
  [150000, 'kingdom-sized, borders included'],
  [400000, 'the size of a storm front, and louder'],
  [1200000, 'as long as a coastline, and twice as ragged'],
  [4000000, 'continent-sized; the maps will need redrawing'],
];

/**
 * A size comparison for a dragon of this body length in DISPLAY meters (sel.dragonInfo passes
 * sel.displayMeters, so a Mountain wyvern compares at its true scale): "newt-sized", "dog-sized"...
 * up to thousands of kilometers.
 */
export function sizeWord(meters: number): string {
  for (const [under, word] of SIZE_BANDS) if (meters < under) return word;
  return 'larger than the map it is on';
}

// ---- Knight height ----
// The running gag (PLAN §3.1). The UI shows it under "Your knights stand {height} tall", so each rung
// is the comparison clause that follows the comma (lowercase start, full stop at the end): awe
// first, then the dry twist. Display meters.
// Anchors: 1.8 m · ~200 m Mountain · ~5 km Kingdom · ~50 km Sky · ~5,000 km World · ~500,000 km Moon ·
// ~10 million km Sun · ~10 billion km Orbits · ~100,000 ly Galaxy · ~90 billion ly Cosmos.
const LY = 9.4607e15;
const HEIGHT_BANDS: readonly (readonly [number, string])[] = [
  [3, 'the traditional height for a knight. For now.'],
  [12, 'tall enough to look a barn in the eye, and win.'],
  [40, 'taller than the church steeple. The bell-ringer waves, nervously.'],
  [120, 'taller than the old oak on the hill, and the hill. The hill is sulking.'],
  [700, "taller than the cathedral they swore to protect. They're trying not to step on it."],
  [2000, 'tall enough that eagles stop halfway up for a rest.'],
  [12000, 'tall enough that castles are pebbles. They shake them out of their boots each evening.'],
  [30000, 'tall enough to wear the weather. Thunderstorms perch on their shoulders like pigeons.'],
  [200000, 'tall enough that the sky only reaches their belts. Their helmets are up with the stars.'],
  [1.5e6, 'tall enough that the horizon curves politely around their boots.'],
  [1.5e7, 'half as tall as the world is wide, and balancing on it like a circus ball.'],
  [1.5e8, 'tall enough to use the world as a footstool. The world is being very patient.'],
  [3e9, 'taller than the moon is far away. They could flick it. They have been asked not to.'],
  [1e11, 'tall enough that the sun would make a modest shield boss. They have asked.'],
  [1e12, 'tall enough to step from planet to planet, if the planets would hold still.'],
  [1e14, 'taller than the solar system is wide. The planets circle their ankles like anxious dogs.'],
  [0.5 * LY, 'tall enough that light packs a lunch to get from their boots to their plumes.'],
  [1000 * LY, 'tall enough to wade between the stars. The small ones get caught in their chainmail.'],
  [1e6 * LY, 'as tall as the galaxy is wide. It makes a handsome cloak brooch.'],
  [1e9 * LY, 'tall enough to herd galaxies like sheep, and lose count.'],
  [2e11 * LY, 'as tall as the observable universe, which is now mostly observing them.'],
];

/**
 * How tall the knights stand, as the clause after "Your knights stand {height} tall," ("taller than
 * the cathedral they swore to protect..."). Takes display meters (state.height).
 */
export function heightWord(displayMeters: number): string {
  for (const [under, word] of HEIGHT_BANDS) if (displayMeters < under) return word;
  return 'taller than anything that has a name. The heralds have started inventing numbers.';
}

// ---- Tiers, bosses, champions, heraldry, abilities ----

/** Per tier: its name, the Roman numeral on the title card, and the card's line. */
export const TIER_TEXT: readonly { name: string; numeral: string; card: string }[] = [
  // The Meadow's card is the title screen's tagline.
  { name: 'The Meadow', numeral: 'I', card: 'An epic of ever-increasing proportions.' },
  // Reserved for the zoom card (lead decision): use this line nowhere else.
  { name: 'The Mountain', numeral: 'II', card: 'Every dragon is a scale on a bigger dragon.' },
];

/**
 * Bosses by id: name + epithet (joined like a dragon's: a leading ',' attaches with no space),
 * the arrival line (bossSummon) and the fall line (bossDefeated).
 */
export const BOSS_TEXT: Readonly<Record<string, { name: string; epithet: string; arrive: string; fall: string }>> = {
  elderNewt: {
    name: 'The Elder Newt',
    // Quiet foreshadowing of the Ouroboros; dragon epithets no longer use this line.
    epithet: ', Who Was Here First',
    arrive: 'The sky darkens. Something older than the hills has been woken, and it was having a lovely nap.',
    // Leads straight into the Zoom: the music drops out under it.
    fall: 'The Elder Newt falls. Far beneath the meadow, something much larger rolls over.',
  },
  grimmaw: {
    name: 'Grimmaw',
    epithet: 'of the Peaks',
    arrive: 'An avalanche is coming uphill. It has wings. It is Grimmaw.',
    fall: 'Grimmaw falls. His mantle of snow reaches the lowlands next week, as weather.',
  },
};

/**
 * Champions: name, title (joined like an epithet), special move, the join line, idle quips.
 * Quips may contain {height}: the knights' display height, formatted like the headline ("212 m").
 * Ser Aldric's quips play from 1.8 m upward, so none assumes he is already huge.
 */
export const CHAMPION_TEXT: Record<ChampionId, { name: string; title: string; special: string; join: string; quips: string[] }> = {
  aldric: {
    name: 'Ser Aldric',
    title: 'the Mostly Brave',
    special: 'Heroic Lunge',
    join: 'Ser Aldric the Mostly Brave has joined your cause. His knees are steady. Mostly.',
    quips: [
      'For glory! And, time permitting, lunch.',
      'I was never afraid. I was reconnoitring. From behind you.',
      'Stand back, everyone. I am about to lunge.',
      '{height} tall and still mostly brave.',
      'Courage is ninety parts of knighthood. I have the other ten.',
      'Is it looking at me? Tell it I have a prior engagement.',
      'Mother said I would grow into this armour. The armour kept up.',
      'Bravery is doing it anyway. I do it anyway. Eventually.',
    ],
  },
  brunhild: {
    name: 'Dame Brunhild',
    title: ', Who Fears Nothing Except Geese',
    special: 'Hundred-League Swing',
    join: 'Dame Brunhild, Who Fears Nothing Except Geese, has joined your cause. She has asked twice about geese.',
    quips: [
      'Dragons, gladly. Geese, never.',
      'Hold the line! If anything honks, hold it without me.',
      'A goose is just a dragon that has chosen cruelty.',
      '{height} tall, and I still check the sky for geese.',
      'Stand clear. This sword does not do small swings.',
      'Is that a dragon? Oh, thank goodness. I thought it was a goose.',
      'I have climbed bigger mountains. Admittedly, they were not breathing.',
      'I fear nothing. I respect geese, from a very great distance.',
    ],
  },
};

/** Heraldic charges (bought with Scales): the name on the shield and a flavor line (never the effect). */
export const CHARGE_TEXT: Record<ChargeId, { name: string; flavor: string }> = {
  lion: { name: 'Lion Rampant', flavor: 'Up on its hind legs, claws out, tongue out. No herald has ever drawn one sitting down.' },
  sun: { name: 'Sun in Splendour', flavor: 'A blazing sun with a smug little face. Heralds call this "in splendour".' },
  wyvern: { name: 'Wyvern Displayed', flavor: 'Wings spread, belly showing. Your knights study it closely for the soft bits.' },
  stag: { name: 'Stag Courant', flavor: 'Running flat out across the shield, as if late for something. The army takes the hint.' },
  tower: { name: 'Tower Triple-Towered', flavor: 'A tower with towers on it. Somebody is always home, and already armed.' },
  crown: { name: 'Crown Imperial', flavor: 'Many knights, one colossus, one crown. The goldsmith has been told to think big.' },
};

/** Abilities (keys 1-3). */
export const ABILITY_TEXT: Record<AbilityId, { name: string; flavor: string }> = {
  charge: { name: 'Charge!', flavor: 'Everyone, all at once, very fast, in roughly the right direction.' },
  rally: { name: 'Rally', flavor: 'Up goes the banner, and your sword arm stops waiting to be asked.' },
  volley: { name: 'Dragonbane Volley', flavor: 'The sky goes dark with arrows. Somewhere, a fletcher weeps with pride.' },
};

// ---- Microcopy ----
/** Upgrade-offered toasts. The upgrade's name leads so the player knows what just appeared. */
const UPGRADE_TOASTS: Record<UpgradeId, string> = {
  pointySwords: 'The smithy has made a breakthrough.',
  keenEye: 'Someone has noticed the glowing bit.',
  drillSergeant: 'A man with a very loud voice has applied.',
  bounty: 'The crown now pays by the newt.',
  fletching: 'The fletchers have had a long think about feathers.',
  warHorns: 'Someone found the horns. Mind your ears.',
  heroicExample: 'The troops have started copying you.',
  quickNock: 'The archers have been practising the fast part.',
  grindstone: 'The blacksmith bought a bigger wheel.',
  highForge: 'The smiths have lit a forge above the clouds.',
  pikeWall: 'Someone has made the sticks much, much longer.',
  yewLongbows: 'The bowyers have found the yew forests. All of them.',
  mountainTithe: 'The crown has discovered that mountains are taxable.',
  couchedLances: 'The lancers have agreed which end goes forward.',
  destriers: 'Bigger horses have arrived. They seem unbothered.',
};

/**
 * UI microcopy. `unlock.<flag>` keys match the progressive-disclosure flags (ARCHITECTURE.md §4),
 * e.g. MICROCOPY['unlock.unit.archer'] is the toast when archers appear; an empty string means "no
 * toast". Upgrades have per-id toasts (`unlock.upgrade.<id>`) with `unlock.upgrade` as fallback.
 * Milestone toasts: `milestone.<unit>.<owned>` (10, 25, 50, 100, 200, 300, 400, 500), fallback
 * `milestone`. Tokens the UI fills in: {mult}, {owned}, {plural}, {unit}; (M2) {amount}, {scales},
 * {fusion}, {height}, {key}, {name}, {level}, {special}. `tier.<n>` names the tier.
 */
export const MICROCOPY: Readonly<Record<string, string>> = {
  title: 'SCALE',
  tagline: 'An epic of ever-increasing proportions.',
  clickToStart: 'Click to draw your sword.',

  // First-minute hints, in the order a new player meets them.
  hintFirstKill: 'The first dragon falls. The songs will be short.',
  hintHireFootman: 'Glory is better shared. Hire a Footman.',
  hintArmy: "Your footmen fight on their own. They'd still like you to watch.",
  hintGrowth: 'Each dragon is a little bigger than the last. Nobody finds this reassuring.',
  hireFootman: 'Hire a Footman',

  // Coach marks, drawn on the stage beside the glowing weak spot (render/fx/coach.ts). Line 1 is
  // Cinzel caps (a call to action, read at a glance: the stagger one shows for a 1.2 s windup),
  // line 2 EB Garamond italic. {mult} is the live weak-spot multiplier (5, or 10 with Keen Eye).
  // The weak-spot coach can sit on a loose scale, a glowing throat or a tail base, so line 1 names
  // the glow, not the body part. The stagger coach only shows once the glow is learned, so its
  // line 1 teaches the timing alone; the ring already says where. Clarity on line 1, wink on line 2.
  coachWeakSpot: 'Strike where it glows',
  coachWeakSpotSub: "×{mult} damage. It's a sore spot.",
  coachStagger: 'Strike now!',
  coachStaggerSub: 'Interrupt it for bonus gold',
  // Caption under the first few crit numbers, naming the cause. A label, not a joke.
  critCaption: 'Weak spot ×{mult}',

  // HUD and panel labels.
  'tier.0': 'The Meadow',
  'tier.1': 'The Mountain',
  'panel.armyEmpty': 'No one has answered the call. Yet.',
  'panel.upgradesEmpty': 'Every upgrade bought. The smiths are thinking very hard.',

  // Stagger callout (big word) and its sub-line.
  stagger: 'STAGGERED!',
  staggerSub: 'Bonus gold for the rude interruption.',

  // Unlock toasts.
  'unlock.feature.dragonBar': '',
  'unlock.feature.gold': 'Gold! The newt had savings.',
  'unlock.unit.footman': 'Footmen may now be hired. They bring their own soup.',
  'unlock.feature.panel': "The muster roll is open. It's a short roll.",
  'unlock.unit.archer': 'Archers join the muster. Stand well clear of the pointy rain.',
  // The Mountain. (Scales announce themselves through scalesGain, so their unlock stays quiet.)
  'unlock.unit.lancer': 'Lancers may now be hired. Each horse is the size of a cathedral, and as hard to steer.',
  'unlock.feature.heraldry': 'Heraldry is open. Spend Scales on a coat of arms your whole army will wear.',
  'unlock.feature.scales': '',
  'unlock.ability.charge': 'Charge! is ready. Press 1, and try to keep up.',
  'unlock.ability.rally': 'Rally is ready. Press 2 and raise the banner.',
  'unlock.ability.volley': 'Dragonbane Volley is ready. Press 3. Mind your heads.',
  // Short toasts; CHAMPION_TEXT[id].join is the longer introduction (different joke, so both can show).
  'unlock.champion.aldric': 'A champion rides in: Ser Aldric the Mostly Brave!',
  'unlock.champion.brunhild': 'A champion strides in: Dame Brunhild! No geese reported.',

  // The Wyrm Gauge and bosses. gaugeHint is the one-time caption when the gauge first appears.
  gauge: 'Wyrm Gauge',
  gaugeHint: 'Each kill loosens a scale. Somewhere, something very large has started to itch.',
  bossTimer: 'Before it escapes',
  bossEscaped: 'It has slipped away to sulk. Loosen a few more scales and it will be back.',

  // The Zoom. zoomPreview: {scales} is the Scales earned, {fusion} the bare Fusion Bonus number
  // (the × is in the template), {height} the formatted height ("212 m").
  zoomButton: 'Zoom',
  zoomButtonSub: 'Fuse your army into one colossal knight. Then look down.',
  zoomPreview: '+{scales} Scales · Fusion Bonus ×{fusion} · Knights {height} tall',
  zoomPush: 'Or fight on: every dragon you add now makes a mightier colossus.',
  zoomLocked: 'The Kingdom arrives in the next build. The masons are still making the castles small enough.',
  scalesGain: '+{amount} Scales',
  heightHeadline: 'Your knights stand {height} tall',

  // After the first zoom (coach mark: line 1 Cinzel caps, line 2 italic).
  coachHeraldry: 'Spend your Scales',
  coachHeraldrySub: 'Your coat of arms flies on every banner, at every size.',
  // Ability coach mark: {key} is the hotkey, {name} the ability ("Press 1: Charge!").
  coachAbility: 'Press {key}: {name}',

  // Champions and Heraldry panels.
  'tab.champions': 'Champions',
  'tab.heraldry': 'Heraldry',
  championLevel: 'Level {level}',
  championSpecial: 'Special: {special}',
  'panel.championsEmpty': 'No champions yet. The bravest ones are always running late.',
  'panel.heraldryIntro': 'Spend Scales on charges for your coat of arms. It flies on every banner, and it never comes down.',
  'unlock.upgrade': 'New upgrade available.',
  ...Object.fromEntries(
    (Object.keys(UPGRADE_TOASTS) as UpgradeId[]).map((id) => [
      'unlock.upgrade.' + id,
      `${UPGRADE_TEXT[id].name}: ${UPGRADE_TOASTS[id].charAt(0).toLowerCase()}${UPGRADE_TOASTS[id].slice(1)}`,
    ]),
  ),

  // Milestone toasts (each is a damage multiplier for that unit type).
  milestone: '{plural} ×{mult} damage: {owned} strong, and it shows.',
  'milestone.footman.10': 'Footmen ×{mult}: ten of them now, which is technically a crowd.',
  'milestone.footman.25': 'Footmen ×{mult}: twenty-five strong. They have formed a choir.',
  'milestone.footman.50': 'Footmen ×{mult}: fifty. The soup budget is under review.',
  'milestone.footman.100': 'Footmen ×{mult}: a hundred. The meadow is now mostly footmen.',
  'milestone.footman.200': 'Footmen ×{mult}: two hundred. Nobody can see the meadow anymore.',
  'milestone.footman.300': 'Footmen ×{mult}: three hundred. The soup is now a lake.',
  'milestone.footman.400': 'Footmen ×{mult}: four hundred. Marching in step makes the hills bounce.',
  'milestone.footman.500': 'Footmen ×{mult}: five hundred. Legally, this is a nation.',
  'milestone.archer.10': 'Archers ×{mult}: ten bows. Briefly, the sky is more arrow than sky.',
  'milestone.archer.25': 'Archers ×{mult}: twenty-five. The birds have filed a complaint.',
  'milestone.archer.50': 'Archers ×{mult}: fifty. Each volley casts its own shadow.',
  'milestone.archer.100': "Archers ×{mult}: a hundred. It's raining, technically.",
  'milestone.archer.200': 'Archers ×{mult}: two hundred. The weather forecast is now arrows.',
  'milestone.archer.300': 'Archers ×{mult}: three hundred. Every goose in the county has left.',
  'milestone.archer.400': 'Archers ×{mult}: four hundred. They no longer aim. They simply occur.',
  'milestone.archer.500': 'Archers ×{mult}: five hundred. The sun has stopped trying.',
  'milestone.lancer.10': 'Lancers ×{mult}: ten riders. The mountain twitches at every charge.',
  'milestone.lancer.25': 'Lancers ×{mult}: twenty-five. The avalanche warnings are now about them.',
  'milestone.lancer.50': 'Lancers ×{mult}: fifty. Three kingdoms away, the teacups rattle.',
  'milestone.lancer.100': 'Lancers ×{mult}: a hundred. The horses graze on pine forests like clover.',
  'milestone.lancer.200': 'Lancers ×{mult}: two hundred. The dust cloud has its own weather.',
  'milestone.lancer.300': 'Lancers ×{mult}: three hundred. From afar, the lances look like a very angry forest.',
  'milestone.lancer.400': 'Lancers ×{mult}: four hundred. The stable bill has been referred to the crown.',
  'milestone.lancer.500': 'Lancers ×{mult}: five hundred. The horizon is mostly horse.',
};
