// Player-facing text for the core content. The writer (WP 1.8) owns the strings in this file; the
// economy WP (1.5) owns its exported SHAPES (keep them): UNIT_TEXT, UPGRADE_TEXT, dragonName,
// sizeWord, MICROCOPY. Placeholder strings below until the writer fills them.
// Pure: no randomness except the injected `rand`, no imports beyond core types.
// Effect lines ("Click damage ×2") are generated by the UI from data; never write them as flavor.
import type { UnitId, UpgradeId } from '../types';

export const UNIT_TEXT: Record<UnitId, { name: string; plural: string; flavor: string }> = {
  footman: { name: 'Footman', plural: 'Footmen', flavor: 'Brave, mostly. Paid in soup.' },
  archer: { name: 'Archer', plural: 'Archers', flavor: 'Aims for the eyes. Hits the general area.' },
};

export const UPGRADE_TEXT: Record<UpgradeId, { name: string; flavor: string }> = {
  pointySwords: { name: 'Pointier Swords', flavor: 'Research confirms the pointy end is the important end.' },
  drillSergeant: { name: 'Drill Sergeant', flavor: 'Left, right, stab.' },
  keenEye: { name: 'Keen Eye', flavor: 'That scale is loose. You can tell.' },
  fletching: { name: 'Honest Fletching', flavor: 'The feathers go at the back.' },
  bounty: { name: 'Bounty Notices', flavor: 'WANTED: dragons. Any size.' },
  warHorns: { name: 'War Horns', flavor: 'Nobody fights well to silence.' },
  heroicExample: { name: 'Heroic Example', flavor: 'Where you strike, they follow.' },
  quickNock: { name: 'Quick Nock', flavor: 'Less aiming, more arrows.' },
  grindstone: { name: 'Grindstone', flavor: 'Your sword, but more so.' },
};

// ---- Dragon names ----
const NAMES: readonly string[] = [
  'Pumpernickel',
  'Smoulderbottom',
  'Gribble',
  'Nibwort',
  'Vexathrax',
  'Snorrow',
  'Pip',
  'Cinderwick',
  'Old Muddle',
  'Brisket',
];

const EPITHETS: readonly string[] = [
  'the Unready',
  'the Mildly Singed',
  'the Damp',
  'Who Bites Ankles',
  'the Unexpectedly Loud',
  'the Moderately Fearsome',
  'Eater of One (1) Sheep',
  'the Small',
];

function pick<T>(rand: () => number, list: readonly T[]): T {
  return list[Math.floor(rand() * list.length) % list.length]!;
}

/**
 * Name the nth dragon of a species. Pure: all variation comes from `rand` ([0, 1), seeded by the
 * core), so the same save always names the same dragons. `index` is the dragon's number in its
 * tier (0 = the very first newt), for names that escalate with size.
 */
export function dragonName(rand: () => number, _species: string, _index: number): { name: string; epithet: string } {
  return { name: pick(rand, NAMES), epithet: pick(rand, EPITHETS) };
}

/** A size comparison for a dragon of this body length in meters ("newt-sized", "dog-sized"...). */
export function sizeWord(meters: number): string {
  if (meters < 0.8) return 'newt-sized';
  if (meters < 1.8) return 'dog-sized';
  if (meters < 4) return 'horse-sized';
  if (meters < 8) return 'cart-sized';
  if (meters < 16) return 'barn-sized';
  return 'the size of a barn, if the barn were angry';
}

/**
 * UI microcopy. `unlock.<flag>` keys match the progressive-disclosure flags (ARCHITECTURE.md §4),
 * e.g. MICROCOPY['unlock.unit.archer'] is the toast when archers appear.
 */
export const MICROCOPY: Readonly<Record<string, string>> = {
  title: 'SCALE',
  tagline: 'Every dragon is a scale on a bigger dragon.',
  clickToStart: 'Click to draw your sword.',
  hintWeakSpot: 'Strike the glowing scale.',
  hintStagger: 'Hit the throat while it breathes in!',
  hireFootman: 'Hire a Footman',
  'unlock.feature.dragonBar': '',
  'unlock.feature.gold': 'Gold!',
  'unlock.unit.footman': 'Footmen may now be hired.',
  'unlock.feature.panel': 'The army awaits your orders.',
  'unlock.unit.archer': 'Archers have joined the muster.',
  'unlock.upgrade': 'New upgrade available.',
};
