// The craggy mountain wyvern (tier 1): a species parameter set for the rig (see ./species.ts).
//
// Two hind legs; the wings are its forelegs: it walks on its wing-wrists like a bat or a
// pterosaur, wings folded when grounded (the elbows jut up over the shoulders), spread for display,
// breath and landing. Craggy rock plates run along its back, a crest of stony horns crowns the
// skull, and a long tail ends in a club of rock (or, for some, a spade). Young (0.8 m): a gangly
// fledgling, all head and wings. Old (60 m): a walking crag.
// Type-only imports: species.ts imports this module's value.
import type { Morph, SpeciesDef } from './species';

const WYVERN_YOUNG: Morph = {
  headLen: 0.2,
  neckLen: 0.13,
  bodyLen: 0.25,
  tailLen: 0.42,
  thickNeck: 0.032,
  thickShoulder: 0.07,
  thickBelly: 0.064,
  thickHip: 0.05,
  thickTail: 0.04,
  backShare: 0.5,
  bellyAt: 0.3,
  clearance: 0.1,
  arch: 0.05,
  tilt: 0.24,
  neckRaise: 1.0,
  neckCurl: 0.38,
  headTilt: -0.02,
  tailDroop: 0.12,
  tailCurl: -0.4,
  cranium: 0.4,
  snout: 0.24,
  jaw: 0.2,
  eyeSize: 0.11,
  eyePos: 0.47,
  brow: 0.06,
  teeth: 0.5,
  hornLen: 0.32,
  hornPairs: 1,
  hornCurl: 0.2,
  hornWidth: 0.11,
  gills: 0,
  gillCount: 0,
  whiskers: 0,
  frill: 0,
  legPairs: 1,
  legBend: 1.45,
  legSplit: 0.48,
  legWidth: 0.034,
  footLen: 0.3,
  toes: 3,
  claws: 0.7,
  frontLegAt: 0.06,
  backLegAt: 0.92,
  wingSpan: 0.46,
  wingFingers: 3,
  wingAt: 0.06,
  wingScallop: 0.42,
  buzz: 0,
  crest: 0.016,
  crestSpikes: 8,
  crestSharp: 1,
  crestFrom: 0.62,
  crestTo: 0.93,
  tailFin: 0,
  tailSpade: 0,
  tailClub: 0.028,
  heads: 1,
  wingWalk: 1,
  armBend: 3.2,
  armSplit: 0.36,
  armWidth: 0.03,
  wingRoot: 1.05,
  plates: 0.024,
  plateCount: 6,
  plateFrom: 0.2,
  plateTo: 0.6,
  plateJag: 0.35,
  crownN: 2,
  crownLen: 0.14,
  clubJag: 0.5,
  hornBreak: 0,
  hornGnarl: 0,
};

const WYVERN_OLD: Morph = {
  headLen: 0.125,
  neckLen: 0.17,
  bodyLen: 0.24,
  tailLen: 0.5,
  thickNeck: 0.034,
  thickShoulder: 0.062,
  thickBelly: 0.058,
  thickHip: 0.048,
  thickTail: 0.038,
  backShare: 0.5,
  bellyAt: 0.3,
  clearance: 0.085,
  arch: 0.06,
  tilt: 0.2,
  neckRaise: 0.88,
  neckCurl: 0.46,
  headTilt: -0.08,
  tailDroop: 0.1,
  tailCurl: -0.5,
  cranium: 0.34,
  snout: 0.2,
  jaw: 0.24,
  eyeSize: 0.058,
  eyePos: 0.5,
  brow: 0.1,
  teeth: 1,
  hornLen: 0.62,
  hornPairs: 2,
  hornCurl: 0.4,
  hornWidth: 0.15,
  gills: 0,
  gillCount: 0,
  whiskers: 0,
  frill: 0,
  legPairs: 1,
  legBend: 1.4,
  legSplit: 0.48,
  legWidth: 0.03,
  footLen: 0.3,
  toes: 3,
  claws: 1,
  frontLegAt: 0.06,
  backLegAt: 0.92,
  wingSpan: 0.5,
  wingFingers: 4,
  wingAt: 0.06,
  wingScallop: 0.5,
  buzz: 0,
  crest: 0.024,
  crestSpikes: 14,
  crestSharp: 1,
  crestFrom: 0.6,
  crestTo: 0.93,
  tailFin: 0,
  tailSpade: 0,
  tailClub: 0.04,
  heads: 1,
  wingWalk: 1,
  armBend: 3.2,
  armSplit: 0.36,
  armWidth: 0.03,
  wingRoot: 1.05,
  plates: 0.07,
  plateCount: 9,
  plateFrom: 0.19,
  plateTo: 0.62,
  plateJag: 0.9,
  crownN: 5,
  crownLen: 0.3,
  clubJag: 0.9,
  hornBreak: 0,
  hornGnarl: 0,
};

export const WYVERN: SpeciesDef = {
  id: 'wyvern',
  sizeLo: 0.8,
  sizeHi: 60,
  young: WYVERN_YOUNG,
  old: WYVERN_OLD,
  jitter: {
    headLen: 0.07,
    neckLen: 0.15,
    tailLen: 0.08,
    thickBelly: 0.1,
    neckRaise: 0.1,
    tailCurl: 0.3,
    snout: 0.1,
    eyeSize: 0.1,
    brow: 0.3,
    hornLen: 0.3,
    hornCurl: 0.5,
    wingSpan: 0.12,
    plates: 0.25,
    plateCount: 0.15,
    crownLen: 0.3,
    crest: 0.3,
    tailClub: 0.2,
  },
  // Some carry a spade of bone instead of a club of rock.
  variants: [{ p: 0.35, set: { tailClub: 0, tailSpade: 0.075 } }],
  // Loose plates and the wing-arm joint, never the tail (the swipe windup's target is on the tail):
  // the elbow jutting up over the shoulders, a plate on the rump, the withers, and one high on the
  // flank among the back plates (never the torso's middle: that's a normal hit).
  weakSpots: [
    { at: 0, atVar: 0, side: 0, sideVar: 0, on: 'elbow' },
    { at: 0.84, atVar: 0.1, side: 0.9, sideVar: 0.1 },
    { at: 0.1, atVar: 0.12, side: 0.8, sideVar: 0.15 },
    { at: 0.44, atVar: 0.18, side: 0.84, sideVar: 0.12 },
  ],
  // The tail, well clear of the rump plate (its loose plates never sit on the tail, so the target
  // can stay there at every on-screen size).
  swipeSpotT: 0.6,
  swipeHeadTiers: false,
  behavior: {
    breathHz: 0.34,
    swayAmp: 0.12,
    swayHz: 0.35,
    blinkMin: 2.2,
    blinkMax: 5.5,
    acts: { look: 3, sniff: 1.3, buzz: 0, yawn: 0.4, wag: 0.8, stretch: 1.5 },
    enter: 'glide',
    leave: 'fly',
    swipe: 'slam',
    breath: 'rear',
    snow: 1,
    eyes: ['#ffb347', '#ff9f3a', '#ffc861', '#ff8c42'],
  },
};
