// Public surface of the core. Other folders import from 'core' (this file) or core/decimal,
// core/format, core/content, core/formulas. Everything in core is pure: no DOM, canvas, audio.
export type {
  AbilityId,
  AbilityState,
  Action,
  ChampionId,
  ChampionState,
  ChargeId,
  DebugAction,
  DragonAttack,
  DragonPhase,
  DragonState,
  Emit,
  EventOf,
  GameEvent,
  GameEventType,
  GameState,
  HeraldryState,
  PendingVolley,
  Stats,
  UnitId,
  UpgradeId,
  WyrmState,
  ZoomReward,
  ZoomStage,
  ZoomState,
} from './types';
export { Decimal, D } from './decimal';
export { createInitialState, STATE_VERSION } from './state';
export { tick } from './tick';
export { applyAction } from './actions';
export { serialize, deserialize, toJSON, fromJSON } from './serialize';
export { fmt, setNotation, getNotation, type Notation } from './format';
export {
  TICK_DT,
  BUY_MAX,
  MAX_BUY,
  strikeDamage,
  clickDamage,
  unitDamage,
  unitDps,
  armyDps,
  unitCost,
  maxAffordable,
  upgradeCost,
  milestoneMult,
  milestoneCount,
  milestoneAt,
  unitPeriod,
  weakMult,
  killGold,
  staggerGold,
  dragonMaxHp,
  dragonGold,
  dragonSize,
  wholeCeil,
  wholeNumber,
  // M2
  tierHpMult,
  tierGoldMult,
  tierCostMult,
  bossAt,
  bossMaxHp,
  bossGold,
  damageMult,
  displayMeters,
  heraldryCost,
  championHit,
  championDps,
  championCost,
  abilityCooldown,
  canZoom,
  scalesForZoom,
  fusionForZoom,
  heightForZoom,
} from './formulas';
export {
  BALANCE,
  MICROCOPY,
  UNITS,
  UNIT_IDS,
  UPGRADES,
  UPGRADE_IDS,
  PHASE,
  sizeWord,
  upgradeDefOf,
  type UnitDef,
  type UpgradeDef,
  type UpgradeEffect,
  type Requirement,
  // M2
  KNIGHT_M,
  TIERS,
  tierOf,
  speciesOf,
  lastTier,
  CHARGES,
  CHARGE_IDS,
  ABILITIES,
  ABILITY_IDS,
  CHAMPIONS,
  CHAMPION_IDS,
  TIER_TEXT,
  BOSS_TEXT,
  CHAMPION_TEXT,
  CHARGE_TEXT,
  ABILITY_TEXT,
  heightWord,
  type TierDef,
  type ChargeDef,
  type AbilityDef,
  type ChampionDef,
  type HeraldryEffect,
} from './content';
export { UNLOCK_FLAGS } from './progress';
export { ENTER_WEAK_FROM, phaseProgress, weakSpotFor, weakSpotHittable, weakSpotLive, type WeakSpotKind } from './weakspot';
export * as sel from './selectors';
